use customer_behavior;

select * from customer;

-- Q1 What is the total revenue generated by male vs female customers --

select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2 Which Customer used a discount but still spent more then the average purchase amount --

select customer_id,purchase_amount 
from customer 
where discount_applied="Yes" and purchase_amount>=(select avg(purchase_amount) from customer);

-- Q3 Which are the top 5 product whith the highest average rating --

select item_purchased,cast(avg(review_rating) as decimal(10,2)) as average_product_rating
from customer 
group by item_purchased 
order by average_product_rating desc
limit 5;

-- Q4 Compare the average purchase amount between standard and express shipping. --

select shipping_type,
cast(avg(purchase_amount) as decimal(10,2))
from customer
where shipping_type in ("Standard","Express") 
group by shipping_type;


-- Q5 Do Subscribed customers spend more? Compare average spend and total revenue between suscribers and non-suscribers. --

select subscription_status,
count(customer_id) as total_customers,
cast(avg(purchase_amount) as decimal(10,2)) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;

-- Q6 Which 10 product have the highest percentage of purchases? --

with v1 as 
( select item_purchased,
count(*) as count_item_purchased,
count(*)*100/sum(count(*)) over() as percent_item_count
  from customer
  group by item_purchased)
  select * from v1 
  order by count_item_purchased desc
  limit 10; 

-- Q7 Segment Customers into New,Returning and loyal based on thier total --
-- number of previous purchase, and show the count of each segment.--

with customer_type as (
select customer_id,previous_purchases,
case 
     when previous_purchases=1 then "New"
     when previous_purchases between 2 and 10 then "Returning"
     else "loyal"
     end as customer_segment
from customer)
select customer_segment,count(*) as  number_of_customer
from customer_type
group by customer_segment;

-- Q8 what are the top 3 most purchased porducts within each catergory? --

with item_counts as( 
select category,item_purchased,count(*) as count_item
from customer
group by category,item_purchased),

item_counts1 as(
select *,
row_number() over(partition by category order by count_item desc) as row_number1  
from item_counts)

select * from item_counts1 where row_number1 in (1,2,3);

-- Q9 Are customer who are repeat buyers (more then 5 previous purchase ) also likely to subscribe. --

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5 
group by subscription_status;

-- Q10 What is the revenue contribution of each age group? --

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




